#python3 xgb_applyBDT.py --load_model $EOS/Tau3MuRun3/data/mva_data/classifiers/classifiers_kFold_Optuna_HLT_overlap_LxyS2.0_2024Jul16.pck --data_outdir $EOS/Tau3MuRun3/data/mva_data/output/MTauX/ --save_output --process WTau3Mu --isMC --LxySign_cut 2.0 -d ../outRoot/WTau3Mu_MCanalyzer_2022preEE_HLT_overlap_onTau3Mu_MTau1650.root --tag MTau1650
#python3 xgb_applyBDT.py --load_model $EOS/Tau3MuRun3/data/mva_data/classifiers/classifiers_kFold_Optuna_HLT_overlap_LxyS2.0_2024Jul16.pck --data_outdir $EOS/Tau3MuRun3/data/mva_data/output/MTauX/ --save_output --process WTau3Mu --isMC --LxySign_cut 2.0 -d ../outRoot/WTau3Mu_MCanalyzer_2022preEE_HLT_overlap_onTau3Mu_MTau1700.root --tag MTau1700
#python3 xgb_applyBDT.py --load_model $EOS/Tau3MuRun3/data/mva_data/classifiers/classifiers_kFold_Optuna_HLT_overlap_LxyS2.0_2024Jul16.pck --data_outdir $EOS/Tau3MuRun3/data/mva_data/output/MTauX/ --save_output --process WTau3Mu --isMC --LxySign_cut 2.0 -d ../outRoot/WTau3Mu_MCanalyzer_2022preEE_HLT_overlap_onTau3Mu_MTau1850.root --tag MTau1850
#python3 xgb_applyBDT.py --load_model $EOS/Tau3MuRun3/data/mva_data/classifiers/classifiers_kFold_Optuna_HLT_overlap_LxyS2.0_2024Jul16.pck --data_outdir $EOS/Tau3MuRun3/data/mva_data/output/MTauX/ --save_output --process WTau3Mu --isMC --LxySign_cut 2.0 -d ../outRoot/WTau3Mu_MCanalyzer_2022preEE_HLT_overlap_onTau3Mu_MTau1900.root --tag MTau1900
#python3 xgb_applyBDT.py --load_model $EOS/Tau3MuRun3/data/mva_data/classifiers/classifiers_kFold_Optuna_HLT_overlap_LxyS2.0_2024Jul16.pck --data_outdir $EOS/Tau3MuRun3/data/mva_data/output/MTauX/ --save_output --process WTau3Mu --isMC --LxySign_cut 2.0 -d ../outRoot/WTau3Mu_MCanalyzer_2022preEE_HLT_overlap_onTau3Mu_MTau1950.root --tag MTau1950

#python3 xgb_applyBDT.py --load_model $EOS/Tau3MuRun3/data/mva_data/classifiers/classifiers_kFold_Optuna_HLT_overlap_LxyS2.0_2024Jul16.pck --tag Dstar-studies2022Cv1 --data_outdir /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/ --save_output --process WTau3Mu --data /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/reMini2022/WTau3Mu_DATAanalyzer_ParkingDoubleMuonLowMass_2022Cv1_HLT_overlap.root

python3 xgb_applyBDT.py --load_model $EOS/Tau3MuRun3/data/mva_data/classifiers/classifiers_kFold_Optuna_HLT_overlap_LxyS2.0_2024Jul16.pck --tag Dstar-studies2022Dv1 --data_outdir /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/ --save_output --process WTau3Mu --isMC --data /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/reMini2022/WTau3Mu_DATAanalyzer_ParkingDoubleMuonLowMass_2022Dv1_HLT_overlap.root

python3 xgb_applyBDT.py --load_model $EOS/Tau3MuRun3/data/mva_data/classifiers/classifiers_kFold_Optuna_HLT_overlap_LxyS2.0_2024Jul16.pck --tag Dstar-studies2022Dv2 --data_outdir /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/ --save_output --process WTau3Mu --isMC --data /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/reMini2022/WTau3Mu_DATAanalyzer_ParkingDoubleMuonLowMass_2022Dv2_HLT_overlap.root

python3 xgb_applyBDT.py --load_model $EOS/Tau3MuRun3/data/mva_data/classifiers/classifiers_kFold_Optuna_HLT_overlap_LxyS2.0_2024Jul16.pck --tag Dstar-studies2022Ev1 --data_outdir /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/ --save_output --process WTau3Mu --isMC --data /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/reMini2022/WTau3Mu_DATAanalyzer_ParkingDoubleMuonLowMass_2022Ev1_HLT_overlap.root

python3 xgb_applyBDT.py --load_model $EOS/Tau3MuRun3/data/mva_data/classifiers/classifiers_kFold_Optuna_HLT_overlap_LxyS2.0_2024Jul16.pck --tag Dstar-studies2022Fv1 --data_outdir /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/ --save_output --process WTau3Mu --isMC --data /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/reMini2022/WTau3Mu_DATAanalyzer_ParkingDoubleMuonLowMass_2022Fv1_HLT_overlap.root

python3 xgb_applyBDT.py --load_model $EOS/Tau3MuRun3/data/mva_data/classifiers/classifiers_kFold_Optuna_HLT_overlap_LxyS2.0_2024Jul16.pck --tag Dstar-studies2022Gv1 --data_outdir /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/ --save_output --process WTau3Mu --isMC --data /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/reMini2022/WTau3Mu_DATAanalyzer_ParkingDoubleMuonLowMass_2022Gv1_HLT_overlap.root

python3 xgb_applyBDT.py --load_model $EOS/Tau3MuRun3/data/mva_data/classifiers/classifiers_kFold_Optuna_HLT_overlap_LxyS2.0_2024Jul16.pck --tag Dstar-studies2023Bv1 --data_outdir /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/ --save_output --process WTau3Mu --isMC --data /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/reMini2023/WTau3Mu_DATAanalyzer_ParkingDoubleMuonLowMass_2023Bv1_HLT_overlap.root

python3 xgb_applyBDT.py --load_model $EOS/Tau3MuRun3/data/mva_data/classifiers/classifiers_kFold_Optuna_HLT_overlap_LxyS2.0_2024Jul16.pck --tag Dstar-studies2023Cv1 --data_outdir /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/ --save_output --process WTau3Mu --isMC --data /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/reMini2023/WTau3Mu_DATAanalyzer_ParkingDoubleMuonLowMass_2023Cv1_HLT_overlap.root
python3 xgb_applyBDT.py --load_model $EOS/Tau3MuRun3/data/mva_data/classifiers/classifiers_kFold_Optuna_HLT_overlap_LxyS2.0_2024Jul16.pck --tag Dstar-studies2023Cv2 --data_outdir /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/ --save_output --process WTau3Mu --isMC --data /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/reMini2023/WTau3Mu_DATAanalyzer_ParkingDoubleMuonLowMass_2023Cv2_HLT_overlap.root
python3 xgb_applyBDT.py --load_model $EOS/Tau3MuRun3/data/mva_data/classifiers/classifiers_kFold_Optuna_HLT_overlap_LxyS2.0_2024Jul16.pck --tag Dstar-studies2023Cv3 --data_outdir /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/ --save_output --process WTau3Mu --isMC --data /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/reMini2023/WTau3Mu_DATAanalyzer_ParkingDoubleMuonLowMass_2023Cv3_HLT_overlap.root
python3 xgb_applyBDT.py --load_model $EOS/Tau3MuRun3/data/mva_data/classifiers/classifiers_kFold_Optuna_HLT_overlap_LxyS2.0_2024Jul16.pck --tag Dstar-studies2023Cv4 --data_outdir /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/ --save_output --process WTau3Mu --isMC --data /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/reMini2023/WTau3Mu_DATAanalyzer_ParkingDoubleMuonLowMass_2023Cv4_HLT_overlap.root

python3 xgb_applyBDT.py --load_model $EOS/Tau3MuRun3/data/mva_data/classifiers/classifiers_kFold_Optuna_HLT_overlap_LxyS2.0_2024Jul16.pck --tag Dstar-studies2023Dv1 --data_outdir /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/ --save_output --process WTau3Mu --isMC --data /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/reMini2023/WTau3Mu_DATAanalyzer_ParkingDoubleMuonLowMass_2023Dv1_HLT_overlap.root
python3 xgb_applyBDT.py --load_model $EOS/Tau3MuRun3/data/mva_data/classifiers/classifiers_kFold_Optuna_HLT_overlap_LxyS2.0_2024Jul16.pck --tag Dstar-studies2023Dv2 --data_outdir /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/ --save_output --process WTau3Mu --isMC --data /eos/cms/store/group/phys_bphys/cbasile/Tau3MuFlat_2025Sep30/reMini2023/WTau3Mu_DATAanalyzer_ParkingDoubleMuonLowMass_2023Dv2_HLT_overlap.root